In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

### 1) Найти с помощью NumPy SVD для матрицы

$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}$

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [6]:
U, s, W = np.linalg.svd(A)

V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица U:\n{U}\n')
print(f'Матрица V:\n{V}\n')
print(f'Матрица D:\n{D}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [10]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


### 2) Для матрицы из предыдущего задания найти:

а) евклидову норму;
    
б) норму Фробениуса.

а) $\left \| A \right \|_{E}=\mu_{1}$

In [15]:
print(f'Евклидова норма:\n{s[0]}')

Евклидова норма:
8.824868854820442


б) $\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}$

In [17]:
def norm(s):
    sum = 0
    for i in s:
       sum+=i**2
    print(f'норма Фробениуса:\n{sum**0.5}')

In [18]:
norm(s)

норма Фробениуса:
11.045361017187261
