### 1.1) Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;<br>
АВ и ВА нельзя определить

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;<br>
ВА нельзя определить, размерность АВ $2\times 3$

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;<br>
размерность АВ $8\times 8$, размерность ВА $3\times 3$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$<br>
размерность АВ $4\times 4$, размерность АВ $4\times 4$

### 1.2) Найти сумму и произведение матриц:
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}+
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A*B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}*
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=
\begin{pmatrix}
4+0 & -1-10\\ 
12+0 & -3+0
\end{pmatrix}=
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

$B*A=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}*
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}=
\begin{pmatrix}
4-3 & -8+0\\ 
0+15 & 0+0
\end{pmatrix}=
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [3]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [4]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

In [5]:
B @ A

array([[ 1, -8],
       [15,  0]])

### 1.3) Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-
2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+
4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=
\begin{pmatrix}
3-0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix}=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

### 1.4) Дана матрица 
$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [8]:
A = np.array([[4, 1], [5, -2], [2, 3]])

$AA^{T}=
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}=
\begin{pmatrix}
16+1 & 20-2 & 8+3\\ 
20-2 & 25+4 & 10-6\\ 
8+3 & 10-6 & 4+9
\end{pmatrix}=
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}
$ 

$AA^{T}=
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=
\begin{pmatrix}
16+25+4 & 4-10+6\\ 
4-10+6 & 1+4+9
\end{pmatrix}=
\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}
$ 

In [9]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [10]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

### 1.5) Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [96]:
def multiplication(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
      print(f'Размерности матриц не подходят для умножения')
      return

    C = [[0] * cols_B  for rows in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i][j] += A[i][k] * B[k][j]
    return C

In [102]:
A = np.array([[4, 1], [5, -2], [2, 3]])
B = np.array([[4, 5, 2], [1, -2, 3]])
multiplication(A, B)

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

In [104]:
A @ B

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

### 2.1) Вычислить определитель:

a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=
sinxsinx+cosxcosx=
sin^{2}x+cos^{2}x=1$

б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=
4*5*9=180$

In [2]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(A)

180.0

в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=
1\begin{vmatrix}
5 & 6 
8 & 9 
\end{vmatrix}
-2\begin{vmatrix}
4 & 6 
7 & 9 
\end{vmatrix}
+3\begin{vmatrix}
4 & 5 
7 & 8 
\end{vmatrix}=
1(5*9-6*8)-2(4*9-6*7)+3(4*8-5*7)=-3+12-9=0$

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

### 2.2) Определитель матрицы $A$ равен $4$. Найти:

а)
$det(A^{2})$</br>
$det(AB)=detA\cdot detB => det(A^{2})=detA\cdot detA=4\cdot4=16$

б) 
$det(A^{T})$</br>
$detA^{T}=detA => det(A^{T}) = 4$

в) 
$det(2A)=4 * 2^{n}$</br>
n = размерность матрицы

### 2.3)  Доказать, что матрица A вырожденная.

$A=\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   


1 и 2 строки матрицы линейно зависимы => Определитель матрицы = 0 => матрица выроденная. 

In [17]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

### 2.4) Найти ранг матрицы:

а) 

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

Вторая строка является разницей третьей и первой строк, а значит, ее можно отбросить:

$\begin{pmatrix}
1 & 2 & 3\\  
2 & 3 & 4
\end{pmatrix}$

Вычтем из второй строки первую, умноженную на  2:

$\begin{pmatrix}
1 & 2 & 3\\  
0 & -1 & -2
\end{pmatrix}$

Таким образом, ранг матрицы равен  2

In [19]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б) 

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить.
Также можно переставить четвертую и первую строку местами:

$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 1
\end{pmatrix}$

Первый и второй столбцы также линейно зависимы, а значит можно убрать первый столбец:

$\begin{pmatrix}
3 & 5 & 6\\
0 & 2 & 2\\ 
0 & 2 & 1
\end{pmatrix}$

Вычтем из третьей строки вторую:

$\begin{pmatrix}
3 & 5 & 6\\
0 & 2 & 2\\ 
0 & 0 & -1
\end{pmatrix}$

Таким образом, ранг матрицы равен 3

In [20]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(A)

3